name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./

    # Alternativa para Railway
    - name: Deploy to Railway
      if: false  # Descomente esta linha para usar Railway
      uses: railway-deploy/railway-action@v2
      with:
        api-token: ${{ secrets.RAILWAY_TOKEN }}
        project-id: ${{ secrets.RAILWAY_PROJECT_ID }}

    # Alternativa para Render
    - name: Deploy to Render
      if: false  # Descomente esta linha para usar Render
      uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        deploy-key: ${{ github.sha }}